name: meal_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  converter: ^0.4.0
  duration_picker: ^1.1.1
  flutter:
    sdk: flutter
  pdf: ^3.10.7
  printing: ^5.11.1
  share_plus: ^7.2.1
  transparent_image: ^2.0.1
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: any

flutter:
  uses-material-design: true